### ISSUE TITLE
BDR & Barman?

### ISSUE THREAD

**Issue by spape** [hoegaarden/barman#1]
Hi,

is it possible to use barman with BDR?

In barman I always get the error message that `postgresql_wal_level` has to be `archive` but its `logical` to work with BDR.

Any idea or future plans to support that?

Best Regards

**Comment by alessandroG77** [comment]
Please, can anyone reply to this post??

Two years past!!

**Comment by hoegaarden** [comment]
Hello.

Sorry, I did not see that issue.
This repo is an unmaintained fork of the barman software, I am in no way connected to 2ndQuadrant, the makers of both barman and BDR (IIRC). So please check with them and please do not use my outdated fork. The only reason for my fork (incremental backups) is not valid anymore and implemented in the original version.
I will delete my fork soon.

Bye, Hannes

**Comment by alessandroG77** [comment]
Ok, sorry.

Thanks a lot.
